[package]
name = "nsvg"
version = "0.2.0"
authors = ["nickbrowne <nickbrowne@users.noreply.github.com>"]
repository = "https://github.com/nickbrowne/nsvg"
keywords = ["svg"]
description = "A simple SVG parser and rasterizer using NanoSVG"
license = "Zlib/MIT"
readme = "README.md"

[dependencies]
image = "0.18.0"

[build-dependencies]
bindgen = { version = "0.26.3", optional = true }
cc = "1.0"
