[package]
name = "nsvg"
version = "0.1.0"
authors = ["nickbrowne <nickbrowne@users.noreply.github.com>"]
repository = "https://github.com/nickbrowne/nsvg"
keywords = ["svg"]
description = "A simple SVG parser and rasterizer using NanoSVG"
license = "Zlib/MIT"

[dependencies]
image = "0.18.0"

[build-dependencies]
bindgen = "0.26.3"
cc = "1.0"
